spring.application.name=demo
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ThienNguyenDB;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=13092006
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=50MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:quanlee1309@gmail.com}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
upload.path=${UPLOAD_PATH:D:/demo/upload_img/}
payos.client-id=c564b529-85c6-4e82-9faf-9dc65f871b4f
payos.api-key=db0660fd-c233-4eaf-ad5e-1fee939585f4
payos.checksum-key=3b84b392968781d3e8c4cb887f3d1fb35bba4a74c4b86a897a9c34d695eefbb8
